export const faq : {title : string, content : string}[] = [
    {title : "What’s included in the Free plan?", content : "Projects on the Free plan have access to 10 CMS collections, 1,000 pages, 5MB file uploads, and a free locale to try. You can use this to explore Framer or design templates. To add a custom domain, you’ll need to upgrade to a paid plan."},
    {title : "Which plan is right for me?", content : "Our Free plan is ideal for non-commercial use. The Mini and Basic plans cater to students, freelancers, and small studios. The Pro and Business plans are designed for teams at agencies, startups, and scale-ups who run their full marketing stack on Framer. The Enterprise plan is tailored towards teams that need custom limits, annual billing, and dedicated support.\n"},
    {title : "What happened to the Startup and Scaleup plans?", content : "The Startup plan is renamed to Launch, and the Scaleup plan to Scale. The only thing that’s changed is the name — the price and features remain the same.\n"},
    {title : "How are extra editors billed?", content : "Editors are billed per editor per month and can be added to your workspace or projects at any time. We will notify you when an editor is added to your billing, and you won’t be charged until the next renewal date of your monthly billing cycle. If your workspace includes a mix of plans, editors will be charged and limited according to the highest tier plan."},
    {title : "What happens if I go over a limit?", content : "When you reach certain limits, we will ask you to upgrade your plan in Framer. For other limits, like bandwidth and form entries, we allow you to exceed your limit for one month. You’ll receive a notification via email so you can upgrade your plan accordingly.\n"},
    {title : "What if my open-source or side project receives a lot of traffic?", content : "We can be flexible with our limits for open-source or non-revenue-based side projects. Please contact us to discuss the options.\n"},
    {title : "What payment methods do you offer?", content : "You can pay for your Framer subscription with a credit card or, in some regions, via PayPal. Alternatively, we offer custom billing options, including credit cards or bank transfers, for Enterprise plans.\n"},
    {title : "What is your refund policy?", content : "If you live in the EU or Turkey, you are legally eligible for a refund if your subscription was purchased within the last 14 days. To claim your refund, please contact our Support team; they will cancel your subscription and process the refund.\n"},
]